describe('MinuetChat module', function()
  it('should be able to load', function()
    assert.has_no.errors(function()
      require('MinuetChat')
    end)
  end)

  it('should be able to set up', function()
    assert.has_no.errors(function()
      require('MinuetChat').setup({})
    end)
    assert.is_not_nil(require('MinuetChat').chat)
  end)
end)
